### ISSUE TITLE
Great work! I have some tweaks.

### ISSUE THREAD

**Issue by DezziDez** [bigchirv/docker_sd_webui_gfx1100#2]
First of all, this is awesome work and it works great on my Manjaro setup!

First and most obvious, your link in your readme links to http://localhost:3000/ but your run.sh is set for port 7860 by default. That should probably be changed on one of the two ends just so they match.

Also, consider using the most recent version of the AMD ROCM drivers, https://repo.radeon.com/amdgpu-install/5.5/ubuntu/jammy/amdgpu-install_5.5.50500-1_all.deb instead of amdgpu-install_5.4.50403-1_all.deb I don't see why this wouldn't work. But I am going to test this just in case.

Overall you turned a slightly complicated process into something quick and easy. (Especially for people not running ubuntu)

Very cool and thanks for your work!

**Comment by chirvo** [comment]
Thank you!

Be sure to check out the develop branch, I'm applying your suggestions right away.
